<?php echo $this->doctype(); ?>
<html>
<head>
    <?php
    $this->headLink()
        ->appendStylesheet($this->basePath() . 'css/globalIE.css', "screen", "lte IE 8")
        ->prependStylesheet($this->basePath() . 'css/global.css');
    echo $this->headLink() . PHP_EOL;

    $this->headScript()
        ->offsetSetFile(1, $this->basePath() . 'js/JQuery.js')
        ->offsetSetFile(2, $this->basePath() . 'js/JQueryUImin.js')
        ->offsetSetFile(3, $this->basePath() . 'js/jquery.md5.min.js')
        ->offsetSetFile(5, $this->basePath() . 'js/indexJS.js');
    echo $this->headScript() . PHP_EOL;


    ?>
</head>
<body>
    <?php echo $this->content; ?>
</body>
</html>