<div class="save-popup"></div>
<div class="global-div border" id="global-context-div">
    <div class="logo" id="logo-div">
        <img src="../img/logo-en.png">
        <div class="trig" id="trig"></div>
    </div>
    <div class="menu-container">
        <div class="start-menu" id="context-menu">
            <div id="greeting"><span>Добро пожаловать, </span><b></b></div>
            <button class="btn btn-right" id="btn-logout">Выйти</button>
            <button class="btn btn-right" id="btn-save">Сохранить</button>
            <button class="btn btn-right" id="btn-create">Создать</button>
            <button class="btn btn-right" id="btn-back">Назад</button>
        </div>
    </div>
    <div class="table">
        <div class="labels">
            <div class="table-label" id="table-label-name">Название сериала</div>
            <div class="table-label" id="table-label-season">Номер сезона</div>
            <div class="table-label" id="table-label-episode">Номер серии</div>
            <div class="table-label" id="table-label-delete">Удалить сериал</div>
        </div>
        <div class="serial-list"></div>
    </div>
</div>
