<div class="border" id="border-register">
<?php
    echo $this->form()->openTag($formRegister);

    $type = $formRegister->get('type');
    echo $this->formHidden($type);

    $nickText = $formRegister->get('nick');
    $nickText->setLabel('Введите ваш логин:')
             ->setLabelAttributes(array('class' => 'label'));
    echo $this->formLabel($nickText);
    echo $this->formText($nickText);
    
    $pass = $formRegister->get('pass');
    $pass->setLabel('Введите пароль:')
            ->setLabelAttributes(array('class' => 'label'));
    echo $this->formLabel($pass);
    echo $this->formPassword($pass);
    
    $pass2 = $formRegister->get('pass2');
    $pass2->setLabel('Повторите пароль:')
            ->setLabelAttributes(array('class' => 'label'));
    echo $this->formLabel($pass2);
    echo $this->formPassword($pass2);

?>
    
<div class="captcha" id="captcha">
    <?php echo $recaptcha->getHTML(); ?>
</div>
<?php 
    echo $this->formSubmit($formRegister->get('submit'));
    
    echo $this->formButton($formRegister->get('cancel'),'Отмена');
    
    echo $this->form()->closeTag();
?>
</div>